"""Type stubs for dexpp — static analysis of Android APK / DEX files."""

from collections.abc import Iterator, Sequence
from enum import Enum
from typing import Optional, Union, overload

__version__: str

# ===== free functions =====

def opcode_name(opcode: int) -> str: ...
def to_string(instruction: Instruction) -> str: ...

# ===== enums =====

class InvokeKind(Enum):
    VIRTUAL = ...
    SUPER = ...
    DIRECT = ...
    STATIC = ...
    INTERFACE = ...
    POLYMORPHIC = ...
    CUSTOM = ...

class EdgeOrigin(Enum):
    DECLARED = ...
    CHA_OVERRIDE = ...
    INHERITED_RESOLUTION = ...

class EdgeKind(Enum):
    FALLTHROUGH = ...
    GOTO = ...
    BRANCH_TAKEN = ...
    BRANCH_NOT_TAKEN = ...
    SWITCH_CASE = ...
    SWITCH_DEFAULT = ...
    EXCEPTION = ...

class TypeRefKind(Enum):
    CONST_CLASS = ...
    CHECK_CAST = ...
    INSTANCE_OF = ...
    NEW_INSTANCE = ...
    NEW_ARRAY = ...
    FILLED_NEW_ARRAY = ...

class OperandWidth(Enum):
    SINGLE = ...
    PAIR = ...

class AnnotationVisibility(Enum):
    BUILD = ...
    RUNTIME = ...
    SYSTEM = ...

class ComponentKind(Enum):
    ACTIVITY = ...
    SERVICE = ...
    RECEIVER = ...
    PROVIDER = ...

# ===== identities =====

class MethodId:
    def __init__(self, class_descriptor: str, name: str, proto: str) -> None: ...
    @property
    def class_descriptor(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def proto(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FieldId:
    def __init__(self, class_descriptor: str, name: str, type: str) -> None: ...
    @property
    def class_descriptor(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ===== annotations =====

class TypeRef:
    @property
    def descriptor(self) -> str: ...

class EnumRef:
    @property
    def constant(self) -> FieldId: ...

class FieldRef:
    @property
    def field(self) -> FieldId: ...

class MethodRef:
    @property
    def method(self) -> MethodId: ...

class MethodTypeRef:
    @property
    def proto(self) -> str: ...

class MethodHandleRef:
    @property
    def index(self) -> int: ...

AnnotationValue = Union[
    None, bool, int, float, str,
    TypeRef, EnumRef, FieldRef, MethodRef, MethodTypeRef, MethodHandleRef,
    list["AnnotationValue"], "Annotation",
]

class Annotation:
    @property
    def type_descriptor(self) -> str: ...
    @property
    def visibility(self) -> AnnotationVisibility: ...
    @property
    def elements(self) -> dict[str, AnnotationValue]: ...

# ===== instructions =====

class InstructionBase:
    @property
    def offset(self) -> int: ...
    @property
    def opcode(self) -> int: ...
    @property
    def size(self) -> int: ...

class NopInstruction:
    base: InstructionBase

class GotoInstruction:
    base: InstructionBase
    branch_offset: int

class IfInstruction:
    base: InstructionBase
    branch_offset: int
    reg_a: int
    reg_b: int

class IfZeroInstruction:
    base: InstructionBase
    branch_offset: int
    reg: int

class SwitchCase:
    key: int
    target: int

class SwitchInstruction:
    base: InstructionBase
    payload_offset: int
    reg: int
    is_packed: bool
    cases: list[SwitchCase]

class ReturnInstruction:
    base: InstructionBase
    reg: Optional[int]
    width: OperandWidth

class ThrowInstruction:
    base: InstructionBase
    reg: int

class MoveInstruction:
    base: InstructionBase
    dest: int
    src: int
    width: OperandWidth

class ConstInstruction:
    base: InstructionBase
    dest: int
    value: int
    width: OperandWidth

class ConstStringInstruction:
    base: InstructionBase
    dest: int
    string_index: int

class ConstClassInstruction:
    base: InstructionBase
    dest: int
    type_index: int

class ConstHandleInstruction:
    base: InstructionBase
    dest: int
    index: int

class TypeInstruction:
    base: InstructionBase
    type_index: int
    dest: int
    src: Optional[int]

class FilledNewArrayInstruction:
    base: InstructionBase
    type_index: int
    arg_regs: list[int]

class MonitorInstruction:
    base: InstructionBase
    reg: int
    is_enter: bool

class FillArrayInstruction:
    base: InstructionBase
    reg: int
    payload_offset: int

class CompareInstruction:
    base: InstructionBase
    dest: int
    src_a: int
    src_b: int
    src_width: OperandWidth

class ArrayOpInstruction:
    base: InstructionBase
    value_reg: int
    array_reg: int
    index_reg: int
    is_write: bool
    width: OperandWidth

class FieldInstruction:
    base: InstructionBase
    field_index: int
    value_reg: int
    object_reg: Optional[int]
    is_static: bool
    is_write: bool
    width: OperandWidth

class InvokeInstruction:
    base: InstructionBase
    method_index: int
    arg_regs: list[int]

class InvokeCustomInstruction:
    base: InstructionBase
    call_site_index: int
    arg_regs: list[int]

class UnaryOpInstruction:
    base: InstructionBase
    dest: int
    src: int
    dest_width: OperandWidth
    src_width: OperandWidth

class BinaryOpInstruction:
    base: InstructionBase
    dest: int
    src_a: int
    src_b: int
    width: OperandWidth

class BinaryLitInstruction:
    base: InstructionBase
    dest: int
    src: int
    literal: int

Instruction = Union[
    NopInstruction, GotoInstruction, IfInstruction, IfZeroInstruction,
    SwitchInstruction, ReturnInstruction, ThrowInstruction, MoveInstruction,
    ConstInstruction, ConstStringInstruction, ConstClassInstruction,
    ConstHandleInstruction, TypeInstruction, FilledNewArrayInstruction,
    MonitorInstruction, FillArrayInstruction, CompareInstruction,
    ArrayOpInstruction, FieldInstruction, InvokeInstruction,
    InvokeCustomInstruction, UnaryOpInstruction, BinaryOpInstruction,
    BinaryLitInstruction,
]

# ===== CFG =====

class CfgEdge:
    @property
    def target_block(self) -> int: ...
    @property
    def kind(self) -> EdgeKind: ...
    @property
    def label(self) -> Optional[int]: ...

class BasicBlock:
    @property
    def index(self) -> int: ...
    @property
    def start_offset(self) -> int: ...
    @property
    def end_offset(self) -> int: ...
    @property
    def first_insn(self) -> int: ...
    @property
    def insn_count(self) -> int: ...
    @property
    def successors(self) -> list[CfgEdge]: ...
    @property
    def predecessors(self) -> list[int]: ...
    @property
    def is_handler_entry(self) -> bool: ...

class BasicBlockView(Sequence[BasicBlock]):
    """Read-only, zero-copy sequence of a CFG's blocks."""

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> BasicBlock: ...
    @overload
    def __getitem__(self, index: slice) -> list[BasicBlock]: ...
    def __iter__(self) -> Iterator[BasicBlock]: ...

class Cfg:
    @property
    def blocks(self) -> BasicBlockView: ...
    @property
    def entry(self) -> Optional[BasicBlock]: ...
    def block_at_offset(self, offset: int) -> Optional[BasicBlock]: ...
    @property
    def empty(self) -> bool: ...
    def __len__(self) -> int: ...

# ===== forward references & try blocks =====

class MethodCall:
    @property
    def code_offset(self) -> int: ...
    @property
    def target(self) -> MethodId: ...
    @property
    def kind(self) -> InvokeKind: ...

class FieldAccess:
    @property
    def code_offset(self) -> int: ...
    @property
    def field(self) -> FieldId: ...
    @property
    def is_write(self) -> bool: ...
    @property
    def is_static(self) -> bool: ...

class StringLoad:
    @property
    def code_offset(self) -> int: ...
    @property
    def value(self) -> str: ...

class TypeUse:
    @property
    def code_offset(self) -> int: ...
    @property
    def descriptor(self) -> str: ...
    @property
    def kind(self) -> TypeRefKind: ...

class CatchHandler:
    @property
    def type_descriptor(self) -> str: ...
    @property
    def handler_offset(self) -> int: ...

class TryBlock:
    @property
    def start_offset(self) -> int: ...
    @property
    def end_offset(self) -> int: ...
    @property
    def handlers(self) -> list[CatchHandler]: ...
    @property
    def catch_all_offset(self) -> Optional[int]: ...

class ParameterRegister:
    @property
    def reg(self) -> int: ...
    @property
    def type(self) -> str: ...
    @property
    def is_this(self) -> bool: ...
    @property
    def is_wide(self) -> bool: ...

# ===== handles =====

class ClassRef:
    @property
    def descriptor(self) -> str: ...
    @property
    def is_resolved(self) -> bool: ...
    def resolve(self) -> Optional[Class]: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def declaring_class(self) -> ClassRef: ...
    @property
    def type(self) -> str: ...
    @property
    def access_flags(self) -> int: ...
    @property
    def is_public(self) -> bool: ...
    @property
    def is_static(self) -> bool: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def initial_value(self) -> AnnotationValue: ...

class Method:
    @property
    def name(self) -> str: ...
    @property
    def declaring_class(self) -> ClassRef: ...
    @property
    def return_type(self) -> str: ...
    @property
    def parameters(self) -> list[str]: ...
    @property
    def access_flags(self) -> int: ...
    @property
    def has_code(self) -> bool: ...
    @property
    def is_constructor(self) -> bool: ...
    @property
    def is_static(self) -> bool: ...
    @property
    def is_public(self) -> bool: ...
    @property
    def is_private(self) -> bool: ...
    @property
    def is_abstract(self) -> bool: ...
    @property
    def is_native(self) -> bool: ...
    @property
    def instructions(self) -> list[Instruction]: ...
    @property
    def cfg(self) -> Cfg: ...
    @property
    def register_count(self) -> int: ...
    @property
    def parameter_registers(self) -> list[ParameterRegister]: ...
    @property
    def calls(self) -> list[MethodCall]: ...
    @property
    def field_accesses(self) -> list[FieldAccess]: ...
    @property
    def string_loads(self) -> list[StringLoad]: ...
    @property
    def type_uses(self) -> list[TypeUse]: ...
    @property
    def try_blocks(self) -> list[TryBlock]: ...
    @property
    def annotations(self) -> list[Annotation]: ...

class Class:
    @property
    def name(self) -> str: ...
    @property
    def package(self) -> str: ...
    @property
    def superclass(self) -> Optional[ClassRef]: ...
    @property
    def interfaces(self) -> list[ClassRef]: ...
    @property
    def methods(self) -> list[Method]: ...
    @property
    def fields(self) -> list[Field]: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def access_flags(self) -> int: ...
    @property
    def source_file(self) -> Optional[str]: ...
    @property
    def is_public(self) -> bool: ...
    @property
    def is_abstract(self) -> bool: ...
    @property
    def is_interface(self) -> bool: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def is_enum(self) -> bool: ...

# ===== call graph =====

class CallEdge:
    """Handle to one call-graph edge (one call site -> one possible target)."""

    @property
    def caller_node(self) -> int: ...
    @property
    def callee_node(self) -> int: ...
    @property
    def caller(self) -> CallNode:
        """The calling node (same as graph.nodes[caller_node])."""
    @property
    def callee(self) -> CallNode:
        """The called node (same as graph.nodes[callee_node])."""
    @property
    def kind(self) -> InvokeKind: ...
    @property
    def code_offset(self) -> int: ...
    @property
    def origin(self) -> EdgeOrigin: ...
    @property
    def via_override(self) -> bool:
        """Deprecated: use `origin`. True iff origin == EdgeOrigin.CHA_OVERRIDE.

        Note `not via_override` no longer identifies declared edges — test
        origin == EdgeOrigin.DECLARED instead.
        """
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CallNode:
    """Handle to one call-graph node (a method, defined or external)."""

    @property
    def index(self) -> int: ...
    @property
    def id(self) -> MethodId: ...
    @property
    def resolved(self) -> bool: ...
    @property
    def outgoing(self) -> list[int]:
        """Indices into CallGraph.edges of this node's call sites; see out_edges."""
    @property
    def incoming(self) -> list[int]:
        """Indices into CallGraph.edges of the calls into this node; see in_edges."""
    @property
    def out_edges(self) -> CallEdgeView: ...
    @property
    def in_edges(self) -> CallEdgeView: ...
    @property
    def method(self) -> Optional[Method]:
        """The Method for a resolved node; None for external methods."""
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CallNodeView(Sequence[CallNode]):
    """Read-only, zero-copy sequence of call-graph nodes."""

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> CallNode: ...
    @overload
    def __getitem__(self, index: slice) -> list[CallNode]: ...
    def __iter__(self) -> Iterator[CallNode]: ...

class CallEdgeView(Sequence[CallEdge]):
    """Read-only, zero-copy sequence of call-graph edges."""

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> CallEdge: ...
    @overload
    def __getitem__(self, index: slice) -> list[CallEdge]: ...
    def __iter__(self) -> Iterator[CallEdge]: ...
    def where(
        self, *, origin: Optional[EdgeOrigin] = None, kind: Optional[InvokeKind] = None
    ) -> CallEdgeView:
        """The edges of this view matching every given filter, selected in C++.

        Class-hierarchy fan-out can make a graph tens of millions of edges, so
        filter here rather than in a Python loop, e.g.
        graph.edges.where(origin=EdgeOrigin.DECLARED) for one edge per call site.
        """

class CallGraph:
    @property
    def nodes(self) -> CallNodeView: ...
    @property
    def edges(self) -> CallEdgeView: ...
    def find(self, id: MethodId) -> Optional[CallNode]: ...
    def method_for(self, node: CallNode) -> Optional[Method]: ...
    @property
    def empty(self) -> bool: ...

# ===== class hierarchy =====

class ClassHierarchy:
    def supertypes(self, descriptor: str) -> list[str]: ...
    def subclasses(self, descriptor: str) -> list[str]: ...
    def implementers(self, descriptor: str) -> list[str]: ...
    def all_supertypes(self, descriptor: str) -> list[str]: ...
    def all_descendants(self, descriptor: str) -> list[str]: ...
    def is_subtype_of(self, sub: str, super: str) -> bool: ...
    def is_loaded(self, descriptor: str) -> bool: ...
    def is_interface(self, descriptor: str) -> bool: ...
    @property
    def empty(self) -> bool: ...

# ===== xrefs =====

class StringXref:
    @property
    def referrer(self) -> int: ...
    @property
    def code_offset(self) -> int: ...

class FieldXref:
    @property
    def referrer(self) -> int: ...
    @property
    def code_offset(self) -> int: ...
    @property
    def is_write(self) -> bool: ...
    @property
    def is_static(self) -> bool: ...

class TypeXref:
    @property
    def referrer(self) -> int: ...
    @property
    def code_offset(self) -> int: ...
    @property
    def kind(self) -> TypeRefKind: ...

class MethodXref:
    @property
    def referrer(self) -> int: ...
    @property
    def code_offset(self) -> int: ...
    @property
    def kind(self) -> InvokeKind: ...

class ReferrerView(Sequence[MethodId]):
    """Read-only, zero-copy sequence of the methods xref sites point into."""

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> MethodId: ...
    @overload
    def __getitem__(self, index: slice) -> list[MethodId]: ...
    def __iter__(self) -> Iterator[MethodId]: ...

class Xrefs:
    @property
    def referrers(self) -> ReferrerView: ...
    def referrer_id(self, referrer: int) -> MethodId: ...
    def referrer_method(self, referrer: int) -> Optional[Method]: ...
    def method_refs(self, id: MethodId) -> list[MethodXref]: ...
    def method_refs_by_name(self, name: str) -> list[tuple[MethodId, list[MethodXref]]]: ...
    def field_refs(self, id: FieldId) -> list[FieldXref]: ...
    def field_reads(self, id: FieldId) -> list[FieldXref]: ...
    def field_writes(self, id: FieldId) -> list[FieldXref]: ...
    def string_refs(self, value: str) -> list[StringXref]: ...
    @property
    def referenced_strings(self) -> list[str]: ...
    def type_refs(self, descriptor: str) -> list[TypeXref]: ...
    @property
    def empty(self) -> bool: ...

# ===== analysis context =====

class AnalysisContext:
    @staticmethod
    def from_dex(path: str) -> AnalysisContext: ...
    @staticmethod
    def from_dex_files(paths: list[str]) -> AnalysisContext: ...
    @staticmethod
    def from_apk(path: str, threads: int = 0) -> AnalysisContext:
        """Load every classes*.dex of an APK, in multidex order.

        threads: 0 = automatic, 1 = load on the calling thread only. Extra threads
        are only used when at least 3 DEX entries are deflate-compressed.
        """
    @property
    def classes(self) -> list[Class]: ...
    @property
    def strings(self) -> list[str]: ...
    def find_class(self, descriptor: str) -> Optional[Class]: ...
    @property
    def call_graph(self) -> CallGraph: ...
    @property
    def class_hierarchy(self) -> ClassHierarchy: ...
    @property
    def xrefs(self) -> Xrefs: ...

# ===== APK layer =====

class IntentFilter:
    @property
    def actions(self) -> list[str]: ...
    @property
    def categories(self) -> list[str]: ...
    def has_action(self, name: str) -> bool: ...
    @property
    def is_launcher(self) -> bool: ...

class Component:
    @property
    def kind(self) -> ComponentKind: ...
    @property
    def name(self) -> str: ...
    @property
    def exported(self) -> Optional[bool]: ...
    @property
    def permission(self) -> Optional[str]: ...
    @property
    def intent_filters(self) -> list[IntentFilter]: ...
    @property
    def guarded_by_signature_permission(self) -> bool: ...
    @property
    def is_exported(self) -> bool: ...
    @property
    def is_reachable(self) -> bool: ...

class Manifest:
    @property
    def package(self) -> str: ...
    @property
    def version_code(self) -> Optional[int]: ...
    @property
    def version_name(self) -> Optional[str]: ...
    @property
    def min_sdk(self) -> Optional[int]: ...
    @property
    def target_sdk(self) -> Optional[int]: ...
    @property
    def permissions(self) -> list[str]: ...
    @property
    def declared_permissions(self) -> list[str]: ...
    def declared_permission_protection_level(self, name: str) -> Optional[int]: ...
    @property
    def components(self) -> list[Component]: ...
    def components_of(self, kind: ComponentKind) -> list[Component]: ...
    @property
    def launcher_activity(self) -> Optional[str]: ...
    @property
    def debuggable(self) -> Optional[bool]: ...
    @property
    def allow_backup(self) -> Optional[bool]: ...

class ResourceName:
    @property
    def package(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def entry(self) -> str: ...

class ResourceTable:
    def name_of(self, id: int) -> Optional[ResourceName]: ...
    def resolve_string(self, id: int) -> Optional[str]: ...
    def id_of(self, type: str, entry: str) -> Optional[int]: ...
    @property
    def empty(self) -> bool: ...

class Certificate:
    @property
    def der(self) -> bytes: ...
    @property
    def subject(self) -> str: ...
    @property
    def issuer(self) -> str: ...
    @property
    def serial_hex(self) -> str: ...
    @property
    def not_before(self) -> str: ...
    @property
    def not_after(self) -> str: ...
    @property
    def sha1_hex(self) -> str: ...
    @property
    def sha256_hex(self) -> str: ...
    @property
    def self_signed(self) -> bool: ...

class SigningInfo:
    @property
    def v1(self) -> bool: ...
    @property
    def v2(self) -> bool: ...
    @property
    def v3(self) -> bool: ...
    @property
    def certificates(self) -> list[Certificate]: ...
    @property
    def is_signed(self) -> bool: ...

class Apk:
    @staticmethod
    def open(path: str) -> Apk: ...
    @property
    def entries(self) -> list[str]: ...
    def read(self, name: str) -> Optional[bytes]: ...
    @property
    def manifest(self) -> Optional[Manifest]: ...
    @property
    def resources(self) -> Optional[ResourceTable]: ...
    def resolve_string(self, reference_id: int) -> Optional[str]: ...
    @property
    def signing(self) -> SigningInfo: ...
    def analysis(self) -> AnalysisContext: ...
